[client]
# 사이드바 설정
showSidebarNavigation = false

[theme]
# 다크 테마 설정
base = "dark"
primaryColor = "#1F4E78"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#161B22"
textColor = "#FFFFFF"
font = "sans serif"

[browser]
# 브라우저 설정
serverAddress = "localhost"
serverPort = 8501
gatherUsageStats = false

[logger]
# 로거 설정
level = "info"

[ui]
# UI 설정
hideTopBar = false
